<?php

namespace Unit\Controllers;

use App\Api\Controllers\HistoryController;
use App\Api\Services\StockService;
use DI\Container;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class HistoryControllerTest extends TestCase
{
    private ?HistoryController $historyController;
    private ?StockService $stockService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $container = new Container();
        $this->stockService = $this->createMock(StockService::class);
        $container->set(StockService::class, $this->stockService);

        $this->historyController = new HistoryController($container, $container->get(StockService::class));
    }

    public function testHistoriesEmptyList()
    {
        $request = $this->createMock(ServerRequestInterface::class);

        $response = $this->createMock(ResponseInterface::class);

        $this->stockService->method('histories')->willReturn([]);

        $jsonResponse = $this->historyController->getHistories($request, $response);

        $this->assertSame([], json_decode($jsonResponse->getBody()->getContents()));
    }
}